<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhoneBook.Core.Application\PhoneBook.Core.Application.csproj" />
    <ProjectReference Include="..\PhoneBook.Core.Domain\PhoneBook.Core.Domain.csproj" />
  </ItemGroup>

</Project>
