<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\PhoneBook.Core.Application.Service\PhoneBook.Core.Application.Service.csproj" />
    <ProjectReference Include="..\Core\PhoneBook.Core.Application\PhoneBook.Core.Application.csproj" />
    <ProjectReference Include="..\Core\PhoneBook.Core.Domain\PhoneBook.Core.Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\PhoneBook.Infrastructure.Repository\PhoneBook.Infrastructure.Repository.csproj" />
  </ItemGroup>

</Project>
